main:
  device: cuda
  dataset: replica # scannet
  scene_name: room2 # scene0011_00
  feature_map_path: ./data/Replica_seg/room2
  replica_dataset_gt_path: ./data/Replica/
  scannet_dataset_gt_path: ./data/ScanNet/
  # only for replica
  replica_color_map: ./hovsg/labels/class_id_colors.json
models:
  clip:
    general_type: ViT-L-14
    type:  ViT-H-14 # ViT-L/14@336px # ViT-H-14
    checkpoint: checkpoints/laion2b_s32b_b79k.bin # checkpoints/ovseg_clipl14_9a1909.pth checkpoints/laion2b_s32b_b79k.bin
